core/display.js

On high DPI monitors (retina) browsers will scale everything up so that content is not extremely small and unreadable. This results in the canvas being reporting that it is a mere ratio of the actual physical screen resolution and as a result, the backend server (if server side scaling is set) will be a fraction of the actual resolution. All operations in noVNC are done on the smaller resolution and the browser automatically scales the canvas up by the ratio. While there are more complex methods of accounting for this, it seems that merely disabling smoothing on the canvas fixes the blurriness caused by the scaling. While we could zoom the canvas out by the same ratio and send the real physical resolution to the server, Linux DEs have a hard time with high DPIs and this would introduce …

KASM-1834 high dpi screens blurry

---

app/ui.js
core/display.js
core/rfb.js
vnc.html

New feature to automatically disable smoothing when the canvas is either 1:1 or an even numbered ratio like 1:2 with physical pixels. In other words, if the canvas is zoomed, or if a high dpi screen, the canvas will be zoomed but if the pixel ratio is even, then disable anti-aliasing to avoid a blurry screen.

KASM-1834 added new anti-aliasing feature

---

app/ui.js

Sometimes keys can get stuck down, usually short cut keys like ALT, shift, command, etc. This occurs when users are in a Kasm session and use shortcuts to perform something locally like take a screenshot locally. The javascript does not get the key up events in this scenario. While you can click off and back on the window, this will novnc to send key up events for all down keys. But users instinctively may refresh the page hoping that will clear the issue, unfortunately that makes it worse because noVNC then loses track of what keys it last sent key down events for. This fix is to gracefully disconnect a session on page reload, thus sending key up events for any keys that were down. It does not fix the issue completely but makes it a little easier to deal with.

Attempt to gracefully disconnect when user refreshes

---

app/ui.js
core/rfb.js

Fixes seamless clipboard for Chrome. Chrome recently changed such that a focus change initiated by a user click is not seen as a user driven event and thus clipboard access is blocked.

Fix send clipboard seamless client to server

---

core/display.js
core/rfb.js
tests/README.md

Removes the non-visible canvas. Collect all rects for a frame and push them directly to the visible frame all at once. Removes concept of 'damage' as this is not applicable when going direct to the visible canvas. 
This does cause UDP to show more artifacts as UDP is currently thrown on the canvas the second the rect is received, unlike TCP, where the a frame is cached until complete and drawn at once. The result is artifacts and out of order processing. We will handle UDP on a separate branch after server side changes are complete.
This will require adequate testing with configurations where the client and server resolutions are not the same. This will require adequate testing of various browsers and systems. I have done preliminary testing on Chrome, Firefox, and Safari on MacOS thus …

KASM-3367 Refactor display.js, direct to visible canvas

---

core/rfb.js
core/util/int.js

- Updated `hashUInt8Array` to work on text too since we've been using it for strings and it was producing `0` all the time
- Updated clipboard hash after receiving a clipboard from KasmVNC so we don't end up doing a round-trip and overwrite KasmVNC clipboard type information

KASM-3744 Fix copy/paste for files and folders

---

app/ui.js

This is the minimum functionality I need to embed KasmVNC in an Iframe.
* Adds new URL param show_control_bar, when set to true displays when iframed
* Adds new parent messages when open or close is fired on the control bar

KASM-3891 add URL param to show control bar in iframe

---

app/ui.js
core/rfb.js
vnc.html

This syncs up with the scaling options available in Windows: 
As far as automating actual UI scaling for XFCE this exec will do that: 
```
xfsettingsd --replace --daemon && xfconf-query -v -c xsettings -p /Gdk/WindowScalingFactor -s 2
```
Unfortunately xfce for window scaling only supports 1x or 2x, to facilitate a scaling change like this to automate it we would need the ability to send this to kasmvnc upstream.

KASM-3972 use an array of known scaling values to produce pixel perfect output

---

core/rfb.js

We previously changed the clipboard check from the onfocus change to the mouse down event, because browsers seemed to either change their behavior after a certain version or their behavior is inconsistent with respect to treating a focus change as a user driven event. Since reading the clipboard can only occur on user driven events, we had to move that from onfocus to mouse down, to get consistent results.
The downside to that is that the clipboard is read ever time the use clicks any mouse button inside Kasm. And unfortunately the clipboard API in the browser is super simple. You either read it or you don't, meaning you can't read the size, mime-types, or anything without first calling the read function. If the clipboard happens to have a large amount of data in it, then it blocks the …

KASM-4039 Limit clipboard checks only after a focus change

---

app/ui.js
vnc.html

Fixes #69 , we previously decided to make our noVNC autoconnect but did it in an improper way. I reverted the improper auto connect method and just set autoconnect to true in ui.js, which ensures connection is not attempted until the DOM is ready.

KASM-4400 undid improper method of doing auto connect

---

core/input/keyboard.js

OS shortcuts that result in the browser losing focus can result in KasmVNC being sent a key down for Meta, Shift, Alt, and Ctrl but not the key up event. This leaves keys in a stuck down position on the server. This fix attempts to detect this and send key up events.
Also removed a section of code that would change keyup event for MetaLeft and MetaRight to a Control key up. This was causing legitimate keyup events for metaleft and metaright not being sent, resulting in stuck key down. This was originally implemented for MacOS zooming via the touchpad or cmd+mouse wheel, these actions result in a lot of simulated key presses of control keys being generated by MacOS. After removing the code block, I did not witness any ill behavior in zooming via the touchpad or mouse.
The keyboard behavior …

attempt to clear stuck keys

---

core/input/keyboard.js
core/rfb.js

Sync server and client down keys during a mouse down event. This ensures key modifiers that are stuck down on server are cleared on the next mouse down event. Key modifiers can also modify the right and left click actions on mouse down events.

sync client and server down keys on mouse down too

---

core/display.js

Fixed bug with secondary screens when the browser window was not in focus. Limited the rect buffer size to fix the issue.

KASM-5563 limit secondary screen rect buffer size

---

core/rfb.js

This broadcasts messages to the other windows that they are eligible for a click. If you alt tab between the windows and focus a display it will still trigger a click but there does not seem to be a way around that. This solves a normal user in single or multi monitor mode getting random clicks if they tab off into another program and come back to the window.

Kasm 5598 click focus

---

app/ui.js
app/ui_screen.js
core/rfb.js

This should work cross browser/platform, the current code doesn't work on MacOS for some reason.
Basically, I set the window.name on each of the screens (`primaryWindow` for the primary and `{screenID}` for the secondaries) as that is accessible on the focus change event. Then I check if the lastWindow (a localStorage setting) matches event.currentTarget.name, if it doesn't _sendLeftClickonNextMove is set to true and the localStorage value is set to the window.name.
This means, when clicking between windows the click is processed because the name is different, but when alt+ tab-ing (command + tab on mac) the name is the same and so doesn't send the click.

KASM-5598 Get mouse down working cross browser

---

core/display.js

Increase secondary screen rect buffer size by 10x to account for large fill rects when using an IDE or similar use cases on large resolution screens. Changed to dropping oldest rect first. Added tracking of the dropped rects.

KASM-5720 - Fix artifacts on secondary screens with high resolution

---

app/ui.js

This disables seamless clipboard by default on first init connections to KasmVNC with Firefox or Safari. 
For applications Iframe wrapping the detection is left up to them since query params will always override these default vars. So they would either need to not pass `&clipboard_seamless=true` or explicitly pass `&clipboard_seamless=false` as the default Iframed value is false.

KASM-6045 change logic to have seamless disabled by default for direct KasmVNC connections on Safari and Firefox

---

app/ui.js
core/decoders/qoi/decoder.js
core/decoders/tight.js

This removed the need to use shared array buffers for the QOI workers. Discovered with the video codec work that you need to pass the transferable object back to the thread it came from and null it out for garbage collection to work.

update the QOI code to use transferable object with memory leaks plugged

---

app/ui.js

In certain conditions UI.rfb may not be defined yet when the session timeout interval function is executed.

KASM-7180 Fix race condition bug with rfb not being defined

---

core/display.js

It was observed when loading a instance in Firefox that at certain resolutions and screens with a higher DPI the parent container would be slightly smaller than the canvas used to draw the screen. This pull request address this issue by getting the parent container's size with sub-pixel precision, rounding down to an even number, and using that as the size the screen should be set to.

Fixing screen sizing issue at certain resolutions
